### ISSUE TITLE
PHP 7 compatibility?

### ISSUE THREAD

**Issue by jjanvier** [oliverklee/phpparser#5]
Hello Oliver,

Is your parser compatible with PHP7?
Do you know any limitations that are not handled ?

Regards,
Julien

**Comment by oliverklee** [comment]
Hi @jjanvier, I haven't tested the parser with PHP 7. Most probably, it will not work with PHP 7.

**Comment by oliverklee** [comment]
https://github.com/nikic/PHP-Parser will work with PHP up to 7.2.

**Comment by jjanvier** [comment]
Thanks :) 
I already know about nikic's parser. But I'm looking for one written in Java.
